from enum import Enum

class OrchestratorStage(Enum):
    REQUEST_RECEIVED = "REQUEST_RECEIVED"
    NORMALIZATION = "NORMALIZATION"
    INTENT_DECOMPOSITION = "INTENT_DECOMPOSITION"
    PLANNING_SKELETON = "PLANNING_SKELETON"
    CLARIFICATION_GATE = "CLARIFICATION_GATE"
    DRAFT_SPEC_GENERATION = "DRAFT_SPEC_GENERATION"
    COMPILE = "COMPILE"
    COMPILE_REPAIR = "COMPILE_REPAIR"
    PLAN_MATERIALIZATION = "PLAN_MATERIALIZATION"
    PREVIEW_SIMULATION = "PREVIEW_SIMULATION"
    APPROVAL_GATE = "APPROVAL_GATE"
    EXECUTION = "EXECUTION"
    APPLY_CHANGESET = "APPLY_CHANGESET"
    POST_APPLY_VERIFICATION = "POST_APPLY_VERIFICATION"
    METRICS_AGGREGATION = "METRICS_AGGREGATION"
    COMPLETED = "COMPLETED"

    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    AWAITING_USER = "AWAITING_USER"
